[package]
name = "fourmeme-sdk-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "read"
path = "read.rs"

[dependencies]
dotenvy = "0.15.7"
fourmeme-sdk = { path = ".." }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
